version: '2'

services:
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9002:9000
      - 8002:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-volume:/data

volumes:
  portainer-volume:
