version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.4.2
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data
    environment:
      - 'discovery.type=single-node'
      - 'http.cors.enabled=true'
      - 'http.cors.allow-origin=*'
      - 'http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization'
      - 'http.cors.allow-credentials=true'
      - 'ES_JAVA_OPTS=-Xms512m -Xmx1024m'
    privileged: true
    hostname: elasticsearch
    container_name: elasticsearch
volumes:
  elasticsearch-volume:
    external: false
