version: '3'
services:
  bitbucket:
    image: atlassian/bitbucket-server
    restart: always
    ports:
      - "7990:7990"
      - "7999:7999"
    volumes:
      - bitbucket-volume:/var/atlassian/bitbucket
    environment:
      - 'BITBUCKET_PROXY_NAME='
      - 'BITBUCKET_PROXY_PORT='
      - 'BITBUCKET_PROXY_SCHEME='
      - 'BITBUCKET_DELAYED_START='
      - 'JVM_MINIMUM_MEMORY=1g'
      - 'JVM_MAXIMUM_MEMORY=4g'
    privileged: true
    hostname: bitbucket-server
    container_name: bitbucket-server
volumes:
  bitbucket-volume:
    external: false
